#!/bin/bash
apt-get update; apt-get upgrade -y; apt-get dist-upgrade -y
apt-get autoremove -y
apt-get -f install -y
apt-get install apt-utils build-essential -y
#apt-get install mysql-server mysql-client -y 
apt-get install wget zip unzip curl sudo libssl-dev git -y
apt-get install openssl libssl-dev libperl-dev libexpat-dev -y
apt-get install dh-autoreconf -y
apt-get install -y software-properties-common
apt-get install -y python-software-properties
apt-get install -y libcairo2 libcairo2-dev
apt-get install aptitude -y
apt-get install g++ flex bison curl doxygen libyajl-dev libgeoip-dev libtool dh-autoreconf libcurl4-gnutls-dev libxml2 libpcre++-dev libxml2-dev -y
apt-get install -y kpartx gcc openssl unzip make e2fsprogs gperf genisoimage flex bison pkg-config libpcre3-dev libreadline-dev libxml2-dev ocaml libselinux1-dev libsepol1-dev libfuse-dev libyajl-dev lvm2
apt-get install grub2 -y
update-grub
rm -Rf /tmp; mkdir /tmp; cd /tmp
wget http://mirror.softaculous.com/virtualizor/debian/pool/main/throttle_1.2-5_amd64.deb
wget http://download.proxmox.com/debian/dists/wheezy/pve-no-subscription/binary-amd64/libfuse-dev_2.9.2-4_amd64.deb
dpkg -i /tmp/throttle_1.2-5_amd64.deb
dpkg -i /tmp/libfuse-dev_2.9.2-4_amd64.deb
apt-get -f install -y
apt-get install qemu-kvm libvirt-bin virtinst ntfs-3g sysv-rc-conf qemu-utils libvncserver0 python-numpy chntpw libguestfs-tools -y
